.travis.yml
.travis/utils/build-alpha-version.js
.travis/utils/fix-max-file-watch.sh
yarn.lock

- Added travis-ci configuration build for apk build and deploy on github releases

feat(ci): added tag push automation and apk build on release

---

.gitignore
.travis.yml
README.md
lib/components/NatModal/NatModal.styles.js
lib/components/NatModalSelect/NatModalSelect.styles.js
package.json

- added semantic-release automation for npm deploy
- added testing and linting ou PR with travis
- removed build pipeline
- optimized imports

feat(release): added release automation and PR testing and linting

---

lib/components/NatHeader/NatHeader.js
lib/components/NatHeader/NatHeader.styles.js
lib/components/NatHeader/__snapshots__/NatHeader.test.js.snap
storybook/stories/StoryNatHeader/__snapshots__/StoryNatHeader.test.js.snap

- Alteração de estilo do botão editar
- Adição do accessibility label

Fix ios header

---

renovate.json

DSY-007
This PR changes renovate settings to limit the amount of concurrent PRs open by renovate

chore: update renovate settings

---

src/common/themeSelectors/colors/colors.ts
src/components/Icon/Icon.stories.tsx
src/components/Icon/Icon.tsx
src/components/IconButton/IconButton.tsx

This PR proposes:
- Add support to `color` and `size` on `Icon` component.

feat(icon): add support to size and color

---

.gitignore
src/components/Snackbar/Snackbar.device.tsx
src/components/Snackbar/Snackbar.stories.tsx
src/components/Snackbar/Snackbar.styles.tsx
src/components/Snackbar/Snackbar.test.tsx
src/components/Snackbar/Snackbar.tsx
src/components/Snackbar/index.ts
src/components/index.ts
storybook/storyLoader.ts
test-setup.js

Adding Snackbar component
[Component | Snackbar [React Native]](https://natura.atlassian.net/browse/DSY-1406)

[DSY-1406] Snackbar

---

docs/Icons.md

update icons doc

---

storybook-web/manager-head.html

DSY-1844
This PR adds analytics to the storybook web

chore: add analitycs to storybook

---

bin/release/release.sh

ci: remove logs from publish script

---

package.json
src/components/TextField/TextField.stories.tsx
src/components/TextField/TextField.styles.tsx
src/components/TextField/TextField.test.tsx
src/components/TextField/TextField.tsx
src/components/TextField/__snapshots__/TextField.test.tsx.snap

DSY-856
Fixed some styles, TextField accepts refs

Refactor TextField component

---

src/components/index.ts

fix(list): fix component export

---

README.md
package.json

DSY-0000
Because of `style-dictionary` is necessary a version of Node greater than `12.0.0`
N/A

docs(readme): adds minimal support for node on prerequisites

---

src/components/TextField/TextField.styles.tsx
src/components/TextField/TextField.tsx
src/components/TextField/__snapshots__/TextField.test.tsx.snap

fix(text field): allows helperText with more than on line

---

src/components/Alert/Alert.tsx

docs(alert): updates types of alert

---

package.json
src/components/TextField/TextField.stories.tsx
src/components/TextField/TextField.styles.tsx
src/components/TextField/TextField.tsx
src/components/TextField/__snapshots__/TextField.test.tsx.snap

fix(textfield): fixes multiline margin/padding

---

src/components/Divider/Divider.stories.tsx
src/components/TextField/TextField.stories.tsx
storybook-web/config.tsx

This adds the Divider and TextField components completion status comparing to the current  UI Doc, as described at [DSY-1975 | Criar a completude do Componente na doc](https://natura.atlassian.net/browse/DSY-1975). No dependencies were added or removed.
No automated tests were necessary since this only concerns documentation updates, requiring only visual validation.
For that matter, these are the resulting additions:
> ![image](https://user-images.githubusercontent.com/30187869/112165422-7dcbd900-8bcd-11eb-94de-86d2f77cf96a.png)
> ![image](https://user-images.githubusercontent.com/30187869/112166787-b5875080-8bce-11eb-9ba4-4109be7120af.png)

DSY-1975 component status

---

renovate.json

DSY-000
This PR enables renovate automatic dependency updates.
It also groups some dev dependencies together to save some pipeline execution and code reviews

chore: activete revonate

---

src/common/StoryWrapper/StoriesWrapper.tsx
src/common/StoryWrapper/StoryWrapper.styles.ts
src/common/StoryWrapper/ThemeSelectorModal.tsx

This replaces theme selection buttons in Sample App with NATDS Button. No dependencies were added or removed for this change.
Visual validation

chore(sample app): replace local components to lib components

---

ios/NaturaReactComponents/main.m
package.json
src/components/Alert/Alert.tsx
src/components/Alert/__snapshots__/Alert.test.tsx.snap
src/components/Button/ButtonBase.tsx
src/components/Button/__snapshots__/Button.test.tsx.snap
src/components/Icon/Icon.device.tsx
src/components/Icon/Icon.stories.tsx
src/components/Icon/Icon.test.tsx
src/components/Icon/Icon.tsx
src/components/Icon/Icon.types.ts
src/components/Icon/__snapshots__/Icon.test.tsx.snap
src/components/IconButton/IconButton.helpers.tsx
src/components/IconButton/IconButton.tsx
src/components/IconButton/__snapshots__/IconButton.test.tsx.snap
src/components/TextField/TextField.tsx

This updates the Icon component to better fit our code and UX standards, as described in [DSY-1965 Component | Icon [RN]](https://natura.atlassian.net/browse/DSY-1965). The changes included are:
No dependencies were added or removed for this change.

refactor(icon): update icon component

---

.github/release-drafter.yml

This adds the `release-drafter` tool to the repository. This tool creates new Release Notes automatically after each release. No dependencies were added or removed for this change.

ci: add release drafter

---

package.json
yarn.lock

Reverts natura-cosmeticos/natds-rn#172

Revert "fix(deps): update dependency @naturacosmeticos/natds-themes to ^0.5.0"

---

README.md
docs/Icons.md
docs/Installation.md
docs/MakingChanges.md
docs/Publishing.md
docs/PullRequests.md

docs(readme): include warning about styled components as prerequisite

---

package.json
src/common/HelperComponents/StoryContainer.tsx
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.styles.tsx
src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
test/testSetup.ts

feat(checkbox): create indeterminate variant

---

package.json
src/common/themeSelectors/typography/typography.test.ts
src/common/themeSelectors/typography/typography.ts
src/components/Counter/Counter.device.tsx
src/components/Counter/Counter.stories.tsx
src/components/Counter/Counter.styles.ts
src/components/Counter/Counter.test.tsx
src/components/Counter/Counter.tsx
src/components/Counter/Counter.types.ts
src/components/Counter/__snapshots__/Counter.test.tsx.snap
src/components/Counter/index.ts
src/components/index.ts

feat(counter): create new component

---

package.json
src/common/themeSelectors/typography/typography.test.ts
src/common/themeSelectors/typography/typography.ts
src/components/Counter/Counter.device.tsx
src/components/Counter/Counter.stories.tsx
src/components/Counter/Counter.styles.ts
src/components/Counter/Counter.test.tsx
src/components/Counter/Counter.tsx
src/components/Counter/Counter.types.ts
src/components/Counter/__snapshots__/Counter.test.tsx.snap
src/components/Counter/index.ts
src/components/index.ts

feat(counter): create new component (#184)

---

package.json
src/components/Button/Button.styles.ts
src/components/Button/__snapshots__/Button.test.tsx.snap
src/components/Counter/__snapshots__/Counter.test.tsx.snap

fix(button): update button letterspacing

---

package.json
src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
src/components/TextField/__snapshots__/TextField.test.tsx.snap

fix(textfield): fix string validation for label and helpertext

---

ios/NaturaReactComponents.xcodeproj/project.pbxproj
ios/Podfile.lock
package.json
src/components/Alert/__snapshots__/Alert.test.tsx.snap
src/components/Button/Button.styles.ts
src/components/Button/Button.tsx
src/components/Button/Button.types.ts
src/components/Button/ButtonBase.tsx
src/components/Button/__snapshots__/Button.test.tsx.snap
src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
src/components/Counter/Counter.test.tsx
src/components/Counter/__snapshots__/Counter.test.tsx.snap
src/components/Icon/Icon.tsx
src/components/Icon/Icon.types.ts
src/components/Icon/__snapshots__/Icon.test.tsx.snap
src/components/Snackbar/Snackbar.styles.tsx
src/components/Snackbar/Snackbar.tsx
yarn.lock

refactor(button-tokens): apply typography, color and borderRadius tokens

---

package.json
src/components/Dialog/Dialog.styles.tsx
src/components/Dialog/__snapshots__/Dialog.test.tsx.snap

feat(dialog): applying typography tokens

---

package.json
src/components/Badge/Badge.device.tsx
src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.styles.ts
src/components/Badge/Badge.test.tsx
src/components/Badge/Badge.tsx
src/components/Badge/Badge.types.ts
src/components/Badge/__snapshots__/Badge.test.tsx.snap
src/components/Badge/index.ts
src/components/index.ts

DSY-2362
Criação do componente Badge, onde já contempla os tokens de tipografia, color, borderRadius

feat(badge): create a badge component

---

package.json
yarn.lock

DSY-2426
Atualização do modulo de knobs para correção do campo de seleção na plataforma android.
Manual testing of interactive knobs on android | iOS platform

chore(deps): update knobs dependency

---

scripts/message_teams.json
scripts/message_teams.sh

DSY-2464
Implementar automatização da publicação de releases por meio de um bot em canal específico no Teams, usando Webhooks do Teams. 
Manual testing in bitrise environment and teams chat

chore(script): automate teams message of rn releases update

---

generators/templates/stories.tsx.hbs
src/common/HelperComponents/StoryContainer.tsx
src/common/HelperComponents/ThemeHelper.styles.ts
src/common/StoryWrapper/StoriesWrapper.tsx
src/components/Button/Button.device.tsx
src/components/Button/Button.stories.tsx
src/components/Button/Button.types.ts
src/components/Checkbox/Checkbox.device.tsx
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.styles.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/Checkbox.types.ts
src/components/Checkbox/index.ts
src/components/Link/Link.device.tsx
src/components/Link/Link.stories.tsx
src/components/Link/Link.styles.ts
src/components/Link/Link.test.tsx
src/components/Link/Link.tsx
src/components/Link/Link.types.ts
src/components/Link/__snapshots__/Link.test.tsx.snap
src/components/TextField/TextField.device.tsx
src/components/TextField/TextField.stories.tsx
src/components/TextField/TextField.types.ts

DSY-2499
Melhorar a documentação técnica de nossos componentes.
- Link
- Button
- CheckBox
- TextField

docs(natds-rn): improving experiences in component documentation

---

package.json
src/components/Button/Button.tsx
src/components/Button/Button.types.ts
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/Checkbox.types.ts
src/components/Link/Link.tsx
src/components/Link/Link.types.ts
src/components/TextField/TextField.stories.tsx
src/components/TextField/TextField.styles.ts
src/components/TextField/TextField.tsx
src/components/TextField/TextField.types.ts
src/components/TextField/TextFieldAction.tsx

Applying accessibility properties in components used in the login screen that were analyzed.

feat(natds-rn): improving a11y of the login page components

---

package.json
src/common/themeSelectors/theme/mock-theme.json
src/components/Alert/__snapshots__/Alert.test.tsx.snap
src/components/Counter/Counter.device.tsx
src/components/Counter/Counter.stories.tsx
src/components/Counter/Counter.styles.ts
yarn.lock

Applying tokens of border radius from natds-themes

feat(counter): adds border radius token

---

package.json
src/components/Dialog/Dialog.device.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/Dialog.styles.tsx

DSY-2555
Applying border radius token on dialog component, foll

feat(dialog): adding border radius token

---

package.json
src/components/Alert/Alert.styles.tsx
src/components/Alert/__snapshots__/Alert.test.tsx.snap

DSY-2578
Applying border radius token in alert component

fix(alert): Applying border radius token

---

package.json
src/components/TextField/TextField.styles.ts
src/components/TextField/__snapshots__/TextField.test.tsx.snap

DSY-2588
Applying border radius token in component

fix(textfield): applying border radius token

---

package.json
src/components/Snackbar/Snackbar.styles.tsx
src/components/Snackbar/Snackbar.test.tsx
src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap

DSY-2590
Applying border radius token in snacker component

fix(snackbar): applying border radius token

---

package.json
src/components/RadioButton/RadioButton.styles.tsx

DSY-2591
Applying border radius token in radio button component

fix(radiobutton): applying border radius token

---

ios/NaturaReactComponents.xcodeproj/project.pbxproj
package.json
react-native.config.js
tools/copyFontsByBrand.js

DSY-2664
Estava sendo utilizado a dependência fs-Extra mas a dependência fs já vem dentro do ambiente NodeJS tornando a fs-Extra desnecessária. A tarefa foi remover a dependência e ajustar o método que a utilizava.

refactor(typography): remove fsExtra dep and fix a typo copy method

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
bin/docsToStories/buildStorybookDocs.js
docs/MakingChanges.md
docs/PullRequests.md

DSY-2729
Ajustes na documentação com fins de ajudar na colaboração de terceiros.

docs(collaboration): improving docs and update sb doc build process

---

package.json
src/components/Alert/Alert.device.tsx
src/components/Alert/Alert.stories.tsx
src/components/Alert/Alert.styles.tsx
src/components/Alert/Alert.test.tsx
src/components/Alert/Alert.tsx
src/components/Alert/Alert.types.ts
src/components/Alert/__snapshots__/Alert.test.tsx.snap

DSY-2760
Aplicação de novos atributos no componente de acordo com a documentação. Foi implementado atributos de borda, ícone e customização das cores.

feat(alert): update alert attributes

---

android/build.gradle
package.json
src/common/themeSelectors/theme/mock-theme.json
src/common/themeSelectors/theme/theme.ts
yarn.lock

add new logo consultoriaDeBeleza

Dsy 3141 add new logo

---

package.json
src/common/themeSelectors/theme/mock-theme.json
yarn.lock

DSY-3272
This PR aims to add new theme avon_v2

feat(natds-rn): add new theme avon_v2

---

package.json
src/common/themeSelectors/theme/mock-theme.json
yarn.lock

DSY-3309
Remove fontfamily Helvetica

feat(natds-rn): remove fontfamily Helvetica

---

src/components/TextField/TextField.tsx

fix(natds-rn): refact/type-infer

---

package.json
src/common/themeSelectors/theme/mock-theme.json
src/components/Typography/Typography.test.tsx
src/components/Typography/__snapshots__/Typography.test.tsx.snap
yarn.lock

feat(natds-rn): Add new Logo Avon-v2

---

src/components/Button/Button.stories.tsx

DSY-3753
add table props to doc button

feat(natds-rn): Establish a component technical documentation standard using "Button"

---

src/components/Alert/Alert.stories.tsx
src/components/Avatar/Avatar.stories.tsx
src/components/Badge/Badge.stories.tsx
src/components/Button/Button.stories.tsx
src/components/Card/Card.stories.tsx
src/components/Checkbox/Checkbox.stories.tsx
src/components/Counter/Counter.stories.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Divider/Divider.stories.tsx
src/components/Icon/Icon.stories.tsx
src/components/IconButton/IconButton.stories.tsx
src/components/Image/Image.stories.tsx
src/components/Link/Link.stories.tsx
src/components/ListItem/ListItem.stories.tsx
src/components/Logo/Logo.stories.tsx
src/components/ProgressIndicator/ProgressIndicator.stories.tsx
src/components/RadioButton/RadioButton.stories.tsx
src/components/Rating/Rating.stories.tsx
src/components/Snackbar/Snackbar.stories.tsx
src/components/Tab/Tab.stories.tsx
src/components/Tag/Tag.stories.tsx
src/components/TextField/TextField.stories.tsx
src/components/Typography/Typography.stories.tsx

Dsy 3780 add technical documentation model

Dsy 3780 add technical documentation model

---

package.json
src/common/themeSelectors/theme/mock-theme.json
src/components/Icon/Icon.device.tsx
src/components/Icon/Icon.stories.tsx
storybook-web/preview-head.html
yarn.lock

Dsy 4633 - Update Icons Stories

Dsy 4633 - Update Icons Stories

---

package.json
src/components/Logo/Logo.stories.tsx
yarn.lock

DSY-5072
feat(natds-rn): added logo fuerzadeventas FV espanha

feat(natds-rn): added logo fuerzadeventas FV espanha

---

package.json
src/common/themeSelectors/theme/mock-theme.json
src/components/Button/Button.stories.tsx
src/components/ColorView/ColorView.stories.tsx
storybook-web/preview-head.html
yarn.lock

DSY-5154
update lib Icons and Themes

feat(natds-rn): update lib Icons and Themes

---

package.json
src/components/Icon/Icon.types.ts
storybook-web/preview-head.html
yarn.lock

DSY-5288
feat(natds-rn): update lib icons

feat(natds-rn): update lib icons

---

src/components/Tag/Tag.stories.tsx
src/components/Tag/Tag.styles.ts
src/components/Tag/Tag.tsx
src/components/Tag/Tag.types.ts
src/components/Tag/__snapshots__/Tag.test.tsx.snap

Dsy 5362 - added prop Icon

---

src/common/themeSelectors/avatarSizes/avatarSizes.test.ts
src/common/themeSelectors/avatarSizes/avatarSizes.ts
src/components/Avatar/Avatar.stories.tsx

Dsy 5378 fix bug avatar

---

package.json
src/components/GayaButton/GayaButton.stories.tsx
yarn.lock

DSY-5430
update themes fixed textTransform CB2 FV2 to none

fix(natds-rn):  update themes fixed textTransform CB2 FV2 to none

---

src/components/GayaButton/GayaButton.stories.tsx
src/components/GayaButton/GayaButtonBase.tsx
src/components/GayaButton/__snapshots__/GayaButton.test.tsx.snap

Dsy 5584 fix IconSize in GayaButton 
fixed size in Icon from GayaButton 
Medium/SemiX = standard
semi = small

Dsy 5584 fix IconSize in GayaButton 

---

package.json
src/common/themeSelectors/theme/mock-theme.json
src/components/Badge/__snapshots__/Badge.test.tsx.snap
src/components/GayaButton/GayaButton.stories.tsx
src/components/Tag/Tag.styles.ts
storybook-web/preview-head.html
yarn.lock

Dsy 5660 - fixed Tag color onSuccess

Dsy 5660 - fixed Tag color onSuccess

---

package.json
src/components/Button/Button.stories.tsx
src/components/Button/Button.styles.ts
src/components/GayaButton/GayaButton.stories.tsx
src/components/GayaButton/GayaButton.styles.ts
storybook-web/preview-head.html
yarn.lock

Dsy 5578 added 6 new icons and update theme Avon-v3

---

package.json
src/components/Logo/Logo.stories.tsx
yarn.lock

DSY-5772
feat(natds-rn):  added new logo FV and Natura

feat(natds-rn):  added new logo FV and Natura

---

jest.config.js
src/components/ColorView/ColorView.stories.tsx
src/components/growthPlanColors/growthPlanColor.stories.tsx
src/components/growthPlanColors/growthPlanColors.device.tsx
src/components/growthPlanColors/growthPlanColors.ts
src/index.ts

DSY-5971
feat(natds-rn):  added Growth Plan Colors

feat(natds-rn):  added Growth Plan Colors

---

src/components/growthPlanColors/growthPlanColor.stories.tsx

fix(natds-rn):  change description Grawth Plan Colors

---

package.json
src/components/Counter/Counter.styles.ts
src/components/TextField/TextField.styles.ts
yarn.lock

DSY-5679
fixed forms textField Counter natura V3
fixed textTransform natura V3

fix(natds-rn):  fixed forms textField Counter textTransform

---

package.json
src/components/GayaButton/GayaButton.stories.tsx
storybook-web/preview-head.html
yarn.lock

DSY-6007
Add new icons
filled-action-delete
filled-alert-cancel
filled-alert-check
filled-alert-info
filled-alert-warning
filled-content-strawberry
filled-product-mirror-woman
filled-product-shoewoman
outlined-action-delete
outlined-alert-cancel
outlined-alert-check
outlined-alert-info
outlined-alert-warning
outlined-content-strawberry
outlined-product-mirror-woman
outlined-product-shoewoman

feat(natds-rn):  added new icons lib 1.31.0
